export const Constants = {
	SocketUrl: "http://localhost:3000",
	NoRecordFound: "No Records Found",
	AddItem: "Add a food Item",
	DeleteItem: "Delete a food Item",
	UpdateItem: "Update a food Item",
	RemoveItem: "Remove the Food Item from Menu List",
	ViewItem: "View Food Items",
	ViewAvailableItems: "View Availalble Food Items",
	ViewDiscardedItem: "View Discard MenuItem List",
	ViewMealType: "View Meal Types",
	ViewNotification: "View Notification",
	ViewRecommendation: "View Recommendations",
	ViewVotedItems: "View Voted Item",
	ViewTodaysMenu: "View Today's Menu",
	SendNotification: "Send Notification for Next Day Meal",
	ChooseNextDayFood: "Choose Item for next day",
	SendFeedback: "Send Feedback",
	DetailedFeedback: "Get Detailed Feedback",
	PrepareFood: "Prepare Food",
	ViewLog: "View Logs",
	Logout: "LogOut",
	InValidAction: "Invalid action. Please try again",
	NotificationIdForFoodRecommendation: 4,
	NotificationIdForTodaysPreparedFood: 6,
};
